### ISSUE TITLE
Failed install on vultr ubuntu 17.04

### ISSUE THREAD

**Issue by ookangzheng** [jawj/IKEv2-setup#14] opened 2017-05-27 06:39 UTC
<img width="1228" alt="screen shot 2017-05-27 at 14 39 04" src="https://cloud.githubusercontent.com/assets/6301735/26518788/4b1276fc-42ea-11e7-8461-fdb928d2274b.png">

Vultr fresh installation

**Comment by jawj** [comment] 2017-05-27 11:02
Interesting ... if I have some time I'll see if I can recreate this. I'm guessing you didn't have this problem, @pirate?

**Comment by pirate** [comment] 2017-05-27 14:32
I just tried it on a brand new Vultr $2.50 and was unable to reproduce this.  Now that https://github.com/jawj/IKEv2-setup/pull/15 is merged, try pulling the repo and running `setup.sh` again.
```
                          ./+o+-       root@ike
                  yyyyy- -yyyyyy+      OS: Ubuntu 17.04 zesty
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.10.0-20-generic
           .++ .:/++++++/-.+sss/`      Uptime: 18m
         .:++o:  /++++++++/:--:/-      Packages: 567
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.4.7
       .:+o:+o/.          `+sssoo+/    CPU: Virtual CPU a7769a6388d5 @ 2.394GHz
  .++/+:+oo+o:`             /sssooo.   RAM: 106MiB / 485MiB
 /+++//+:`oo+o               /::--:.
 \+/+o+++`o++o               ++////.
  .++.o+++oo+:`             /dddhhh.
       .+.o+oo:.          `oddhhhh+
        \+.++o+o``-````.:ohdhhhhh+
         `:o+++ `ohhhhhhhhyo++os:
           .o:`.syhhhhhhh/.oo++o`
               /osyyyyyyo++ooo+++/
                   ````` +oo+++o\:
                          `oo++.
```

**Comment by jawj** [comment] 2017-06-01 18:44
I also had no problem on Vultr today, so closing this pending any more details.

**Closed by jawj** 2017-06-01 18:44 UTC
